name: Publish release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          generate_release_notes: true
          body: |

            ## Changes

            <!-- Changes since last release -->

            <!--

            ## Upgrading from a previous version
            No breaking changes.

            -->

