name: Publish release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git describe --tags --always --dirty)
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          generate_release_notes: true
          files: |
            crds-${{ steps.version.outputs.VERSION }}.yaml
          body: |

            ## Changes

            <!-- Changes since last release -->

            <!--

            ## Upgrading from a previous version
            No breaking changes.

            -->

